### ISSUE TITLE
not an issue per se - how to pass car through loop-the-loop

### ISSUE THREAD

**Issue by franMx** [Saarg/Arcade_Car_Physics#1]
Hey, thanks for sharing, indeed a nice ssytem. How would you go for a loop-the-loop? I adjusted motor torque, car can go bout half the loop, where it falls down. If I add some more torque, car control becomes way too difficult. Regards.

**Comment by Saarg** [comment]
I haven't tried this but from a physics point of view torque won't help it's the speed you have going into the loop that matters. increasing the downforce would help too.

if your loop is unrealistic from a physics point of view you can cheat and add a [constant force](https://docs.unity3d.com/Manual/class-ConstantForce.html) and set the relative force y axis to a value forcing the car on the loop.

**Comment by franMx** [comment]
Went with your suggestion, it's going on an extreme loop now without falling down. Thanks!

**Comment by Saarg** [comment]
Cool, I'm closing this issue.
