### ISSUE TITLE
how to use ghost script?

### ISSUE THREAD

**Issue by franMx** [Saarg/Arcade_Car_Physics#2]
Hi again, how do you use the ghost script ? thanks.

**Comment by Saarg** [comment]
I'm working on the script's documentation and will probably improve it on the next update but you can find an example in my [Autober project](https://github.com/Saarg/AutoTober) .

The recording is managed in [GameManager.cs](https://github.com/Saarg/AutoTober/blob/master/Assets/Scripts/GameManager.cs)

**Comment by Saarg** [comment]
There is now an example in the demo scene.
