### ISSUE TITLE
Asset problems in 2018.3.11f1

### ISSUE THREAD

**Issue by edelventhal** [Saarg/Arcade_Car_Physics#3]
There's something wrong with Github maybe, or it's your project?

When I try to clone your repo or download it as a zip, many of the assets are < 1 KB (the PNGs or the sounds for example). And yet on Github they're actual assets. Have you seen anything like this?

I'm able to get your asset store package just fine but I wanted the latest and the greatest. And it seems unclonable, very weirdly.

**Comment by Saarg** [comment]
I'm using [Git-LFS](https://git-lfs.github.com/) for some files, you can find the list in the [gitattributes](https://github.com/Saarg/Arcade_Car_Physics/blob/master/.gitattributes).
If you try to clone it with git-lfs setup it should work, on windows I've often used sourcetree as a gui and if I recall correctly sourcetree will install git-lfs for you.

Edit: if you want the latest it is on develop branch but the develop branch can sometimes contain work in progress.

**Comment by edelventhal** [comment]
Aha. Beaut. Surprised I've never seen this before.  Works great!
