### ISSUE TITLE
Torque vs speed should use RPM

### ISSUE THREAD

**Issue by Sithdown** [Saarg/Arcade_Car_Physics#4]
Arcade Car Physics is very useful! Thanks.

I was adjusting the Motor torque on a car and had some problems trying to replicate a real car's torque curve.

I understand this is ARCADE car physics so some simplifications are made, but the torque curves online are torque vs rpm (as the speed depends on extra factors such as the gear you are on, drag, gravity...)

Example curve:
![image](https://user-images.githubusercontent.com/430612/60492198-c087a800-9caa-11e9-9b1c-5fe65a0201d4.png)

(Ignore the ft lbs, imagine the curve is N/m vs RPM)

Is there an easy way of using torque/rpm curves?

**Comment by Saarg** [comment]
Hi,
As you said the cars are arcade cars and don't have gearboxes but you can edit my scripts to have one and use the wheel colliders rpm for your curve. I have no plan to add this feature as it's not what this package is about.

I have an older script that does what you want but I'm not providing support for it as it's old and unfinished: https://github.com/Saarg/Unity_Assets/blob/master/Cars/car.cs

Have fun!

**Comment by Sithdown** [comment]
It's understandable @Saarg, thank you.
